//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fontify.Properties
{
    using System;
    using System.Drawing;
    using System.IO;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        internal Resources()
        {
        }

        internal static ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    ResourceManager temp = new ResourceManager("Fontify.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        /// <summary>
        /// Logo image
        /// </summary>
        internal static Bitmap Logo
        {
            get
            {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }

        /// <summary>
        /// IRANSans font as byte array
        /// </summary>
        internal static byte[] IRANSans
        {
            get
            {
                object obj = ResourceManager.GetObject("IRANSans", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
